

services:
  app:
    build: 
      context: .
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - database
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"

  database:
    image: postgres:14.6-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=dbname

  redis:
    restart: always
    image: redis:7.2.4-alpine
    hostname: redis

  worker:
    build: 
      context: .
    hostname: worker
    entrypoint: ["sh", "-c", "celery -A proj worker -l info"]
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - redis
      - database

  flower:
    build: 
      context: .
    hostname: flower
    entrypoint: ["sh", "-c", "celery -A proj --broker=redis://redis:6379/0 flower --loglevel=info"]
    env_file:
      - .env
    ports:
      - "5555:5555"
    volumes:
      - .:/app
    depends_on:
      - redis
      - database
