# Generated by Django 4.2.7 on 2024-06-01

from django.db import migrations
import datetime
from django.utils.timezone import utc


def populate_db(apps, schema_editor):
    Airplane = apps.get_model("main", "Airplane")
    Airline = apps.get_model("main", "Airline")
    Flight = apps.get_model("main", "Flight")
    Passenger = apps.get_model("main", "Passenger")
    Ticket = apps.get_model("main", "Ticket")
    User = apps.get_model("users", "User")

    # Creating Airplanes
    airplane1 = Airplane.objects.create(name="Boeing 737", seats=150)
    airplane2 = Airplane.objects.create(name="Airbus A320", seats=160)
    airplane3 = Airplane.objects.create(name="Boeing 777", seats=300)

    # Creating Airlines
    airline1 = Airline.objects.create(name="American Airlines")
    airline2 = Airline.objects.create(name="Delta Airlines")
    airline3 = Airline.objects.create(name="United Airlines")

    # Creating Flights
    flight1 = Flight.objects.create(
        origin="New York",
        destination="Los Angeles",
        departure=datetime.datetime(2024, 6, 1, 10, 0, tzinfo=utc),
        arrival=datetime.datetime(2024, 6, 1, 14, 0, tzinfo=utc),
        airline=airline1,
        airplane=airplane1,
    )
    flight2 = Flight.objects.create(
        origin="San Francisco",
        destination="Chicago",
        departure=datetime.datetime(2024, 6, 2, 12, 0, tzinfo=utc),
        arrival=datetime.datetime(2024, 6, 2, 16, 0, tzinfo=utc),
        airline=airline2,
        airplane=airplane2,
    )
    flight3 = Flight.objects.create(
        origin="Miami",
        destination="Houston",
        departure=datetime.datetime(2024, 6, 3, 15, 0, tzinfo=utc),
        arrival=datetime.datetime(2024, 6, 3, 18, 0, tzinfo=utc),
        airline=airline3,
        airplane=airplane3,
    )

    # Creating Users
    user1 = User.objects.create_user(
        username="john_doe", email="john.doe@example.com", password="password123"
    )
    user2 = User.objects.create_user(
        username="jane_smith", email="jane.smith@example.com", password="password123"
    )
    user3 = User.objects.create_user(
        username="robert_brown",
        email="robert.brown@example.com",
        password="password123",
    )

    # Creating Passengers
    passenger1 = Passenger.objects.create(
        user=user1,
        full_name="John Doe",
        email="john.doe@example.com",
        passport_number="A12345678",
    )
    passenger2 = Passenger.objects.create(
        user=user2,
        full_name="Jane Smith",
        email="jane.smith@example.com",
        passport_number="B87654321",
    )
    passenger3 = Passenger.objects.create(
        user=user3,
        full_name="Robert Brown",
        email="robert.brown@example.com",
        passport_number="C98765432",
    )
    passenger4 = Passenger.objects.create(
        user=user1,
        full_name="Alice Johnson",
        email="alice.johnson@example.com",
        passport_number="D45678901",
    )
    passenger5 = Passenger.objects.create(
        user=user2,
        full_name="Charlie Wilson",
        email="charlie.wilson@example.com",
        passport_number="E23456789",
    )

    # Creating Tickets
    Ticket.objects.create(
        flight=flight1, price=300, class_type="economy", quantity=5
    ).passengers.set([passenger1, passenger4])
    Ticket.objects.create(
        flight=flight1, price=500, class_type="business", quantity=3
    ).passengers.set([passenger2])
    Ticket.objects.create(
        flight=flight2, price=200, class_type="economy", quantity=10
    ).passengers.set([passenger3])
    Ticket.objects.create(
        flight=flight2, price=400, class_type="business", quantity=4
    ).passengers.set([passenger5])
    Ticket.objects.create(flight=flight3, price=150, class_type="economy", quantity=20)
    Ticket.objects.create(flight=flight3, price=350, class_type="business", quantity=6)
    Ticket.objects.create(flight=flight3, price=700, class_type="first", quantity=2)


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(populate_db),
    ]
